#! /usr/bin/env bash

set -e
set -u

if ! test -f README.md
then
    echo "run from the base directory." >&2
    exit 1
fi

compiler="$1"

scratchdir=$(mktemp -d)
cleanup () {
  rm -rf $scratchdir
}
trap cleanup EXIT

echo "TAP version 13"
echo "1..$(echo tests/simple-exec/*.c | wc -l)"

testdir="./tests/simple-exec"
runner="./runners/simple-exec/$compiler"
for t in $testdir/*.c
do
    result="ok"
    if ! timeout 5m $runner $t > $scratchdir/t.out 2>&1
    then
        result="not ok"
    fi

    echo "$result" "$t"
    sed -e 's/^/\#/' $scratchdir/t.out
done
