#! /usr/bin/env python3

import sys
import sqlite3

if len(sys.argv) == 3:
	inp = open(sys.argv[2])
elif len(sys.argv) == 2:
	inp = sys.stdin
else:
	print("bad arguments")
	sys.exit(1)

with sqlite3.connect(sys.argv[1]) as conn:
	conn.execute('''CREATE TABLE IF NOT EXISTS LUT (K TEXT UNIQUE);''')
	conn.execute('DELETE FROM LUT;')
	for l in inp:
		conn.execute('INSERT OR IGNORE INTO LUT(K) VALUES (?);', (l[:-1],))

