#! /usr/bin/env python3

import sys
import sqlite3

found=False
with sqlite3.connect(sys.argv[1]) as conn:
	c = conn.cursor()
	c.execute('''SELECT COUNT(*) FROM LUT WHERE k = ?;''', (sys.argv[2],))
	if c.fetchone()[0] > 0:
		found=True
if not found:
	sys.exit(1)