#! /bin/sh

set -e
set -u

if ! test "x86_64" = "$(uname -m)"
then
    echo "incorrect host for test" 1>&2
    exit 1
fi

CC=ccomp
CFLAGS="-fall -O2"

export CC CFLAGS
exec ./runners/single-exec/posix $1
