#! /usr/bin/env bash

set -e
set -u

t=$1

cat $t

set -x

if ! valgrind --leak-check=no -q tcc "$t" -o "$t.bin"
then
    exit 1
fi

if ! "$t.bin" > "t.output"
then
    exit 1
fi

if test -f "$t.expected"
then
    if ! diff -u "$t.expected" "$t.output"
    then
        exit 1
    fi
fi
